spring.application.name=sales-tax-manager

spring.datasource.url=jdbc:postgresql://db.jnxvsetwrldklkydiwst.supabase.co:5432/postgres?user=postgres&password=post2126
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true
